/**
 * useFlowchartStore.ts
 *
 * Zustand store for the Mermaid flowchart workspace.
 * Tracks the raw mermaid text (loaded from disk), parsed SVG node
 * coordinates, agent node claims, and per-agent task branches
 * that appear as temporary edges on the flowchart.
 */

import { create } from 'zustand'

export interface FlowchartNodeCoords {
  id: string
  label: string
  x: number
  y: number
  width: number
  height: number
}

/** A task branch is a temporary edge drawn from a file node showing what an agent is doing */
export interface TaskBranch {
  agentId: string
  agentName: string
  nodeId: string       // the file/folder node they're working on
  task: string         // short description e.g. "Fixing auth bug"
  icon: string         // emoji icon e.g. "🔧"
}

export interface FlowchartState {
  /** Raw mermaid text read from the project file */
  mermaidText: string
  /** Base mermaid text from the Atlas scanner (structural map) */
  atlasMermaid: string
  /** Absolute path to the .mermaid file being watched */
  filePath: string | null
  /** Parsed SVG node positions (updated after each render) */
  nodes: FlowchartNodeCoords[]
  /** nodeId → creatureId mapping for which agent claims which node */
  claims: Record<string, string>
  /** Active task branches — agentId → TaskBranch */
  taskBranches: Record<string, TaskBranch>
  /** Whether the flowchart panel is visible */
  visible: boolean
  /** Last time the mermaid file was modified (for dirty checking) */
  lastModified: number
  /** Whether we're currently scanning the directory */
  scanning: boolean
  /** The full scanned directory tree for dynamic file fetching */
  atlasTree: any[]
  /** The root node generated by the system */
  rootId: string
  /** Intrinsic dimensions of the rendered SVG */
  dimensions: { width: number; height: number }

  // Actions
  setMermaidText: (text: string) => void
  setAtlasMermaid: (text: string, tree?: any[], rootId?: string) => void
  setFilePath: (path: string | null) => void
  setNodes: (nodes: FlowchartNodeCoords[]) => void
  claimNode: (nodeId: string, creatureId: string) => void
  releaseNode: (nodeId: string) => void
  releaseAllByCreature: (creatureId: string) => void
  setVisible: (v: boolean) => void
  setLastModified: (ts: number) => void
  setScanning: (v: boolean) => void
  setDimensions: (dim: { width: number; height: number }) => void
  setTaskBranch: (branch: TaskBranch) => void
  clearTaskBranch: (agentId: string) => void
  /** Returns the combined mermaid text: atlas base + task branch overlays */
  getComposedMermaid: () => string
}

export const useFlowchartStore = create<FlowchartState>()((set, get) => ({
  mermaidText: '',
  atlasMermaid: '',
  filePath: null,
  nodes: [],
  claims: {},
  taskBranches: {},
  visible: true,
  lastModified: 0,
  scanning: false,
  atlasTree: [],
  rootId: '',
  dimensions: { width: 800, height: 600 },

  setMermaidText: (text) => set({ mermaidText: text }),
  setAtlasMermaid: (text, tree = [], rootId = '') => set({ atlasMermaid: text, atlasTree: tree, rootId }),
  setFilePath: (path) => set({ filePath: path }),
  setNodes: (nodes) => set({ nodes }),
  claimNode: (nodeId, creatureId) =>
    set((s) => ({ claims: { ...s.claims, [nodeId]: creatureId } })),
  releaseNode: (nodeId) =>
    set((s) => {
      const next = { ...s.claims }
      delete next[nodeId]
      return { claims: next }
    }),
  releaseAllByCreature: (creatureId) =>
    set((s) => {
      const next: Record<string, string> = {}
      for (const [k, v] of Object.entries(s.claims)) {
        if (v !== creatureId) next[k] = v
      }
      return { claims: next }
    }),
  setVisible: (v) => set({ visible: v }),
  setLastModified: (ts) => set({ lastModified: ts }),
  setScanning: (v) => set({ scanning: v }),
  setDimensions: (dim) => set({ dimensions: dim }),

  setTaskBranch: (branch) =>
    set((s) => ({ taskBranches: { ...s.taskBranches, [branch.agentId]: branch } })),

  clearTaskBranch: (agentId) =>
    set((s) => {
      const next = { ...s.taskBranches }
      delete next[agentId]
      return { taskBranches: next }
    }),

  getComposedMermaid: () => {
    const s = get()
    const base = s.mermaidText || s.atlasMermaid
    if (!base) return ''

    const branches = Object.values(s.taskBranches)
    if (branches.length === 0) return base

    const lines = base.split('\n')
    const addedNodeIds = new Set<string>()

    // Helper to dynamically recreate folder structure down to the requested file
    const recursivelyTraceFile = (
      nodeIdParts: string[], 
      treeNodes: any[], 
      currentPath: string, 
      depth: number
    ) => {
      // If we've exhausted everything, stop
      if (depth >= nodeIdParts.length || treeNodes.length === 0) return
      
      const targetSegment = nodeIdParts[depth]
      const isFile = depth === nodeIdParts.length - 1

      for (const node of treeNodes) {
        const sanitizeId = (name: string) => name.replace(/[^a-zA-Z0-9_]/g, '_')
        const safeName = sanitizeId(node.name)

        if (safeName === targetSegment) {
          const nextNodeId = currentPath ? `${currentPath}__${safeName}` : safeName

          if (!addedNodeIds.has(nextNodeId)) {
            addedNodeIds.add(nextNodeId)

            if (node.isDir) {
              lines.push(`    ${nextNodeId}["📁 ${node.name}"]`)
              lines.push(`    style ${nextNodeId} fill:#2a2a50,stroke:#66a3ff,stroke-width:2px,color:#ffffff`)
            } else {
              const ext = node.name.includes('.') ? node.name.split('.').pop() : ''
              const iconMap: Record<string, string> = { ts: '🔷', tsx: '⚛️', js: '🟡', html: '🌐', css: '🎨', json: '📋' }
              const icon = iconMap[ext || ''] || '📄'
              
              lines.push(`    ${nextNodeId}["${icon} ${node.name}"]`)
              lines.push(`    style ${nextNodeId} fill:#1a1a44,stroke:#66a3ff,stroke-width:1px,color:#f0f4ff`)
            }

            if (currentPath) {
              lines.push(`    ${currentPath} --> ${nextNodeId}`)
            }
          }

          // Continue tracing its children
          if (node.isDir && node.children) {
            recursivelyTraceFile(nodeIdParts, node.children, nextNodeId, depth + 1)
          }
          break
        }
      }
    }

    // Inject task branch structural tree
    for (const branch of branches) {
      if (branch.nodeId && s.atlasTree.length > 0 && s.rootId) {
        // Break apart the active node string into parts
        const parts = branch.nodeId.split('__')
        
        // Ensure rootId is at origin (parts[0] should equal rootId usually)
        if (parts[0] === s.rootId) {
          recursivelyTraceFile(parts, s.atlasTree, s.rootId, 1)
        }
      }

      const taskNodeId = `task_${branch.agentId.replace(/[^a-zA-Z0-9_]/g, '_')}`
      lines.push(`    ${branch.nodeId} -.-|"${branch.icon} ${branch.agentName}"| ${taskNodeId}["${branch.task}"]`)
      lines.push(`    style ${taskNodeId} fill:#1a1a2e,stroke:#ffdd55,stroke-width:1.5px,stroke-dasharray:5 5,color:#ffdd55`)
    }

    return lines.join('\n')
  },
}))

